### ISSUE TITLE
S3 error: Access Denied

### ISSUE THREAD

**Issue by NicWayand** [Element84/pangeo-deployment#2]
First thanks for sharing this guide!

On the `./deploy` step while creating the stack I get the below S3 error. The IAM role I created as S3 permisions, so I am wondering if its saying I don't have S3 perms for the https://s3.amazonaws.com/e84-pangeo bucket?

"ResourceStatus": "CREATE_FAILED",
            "ResourceStatusReason": "S3 error: Access Denied\nFor more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html",
            "ResourceProperties": "{\"TemplateURL\":\"https://s3.amazonaws.com/e84-pangeo/ops/cf-templates/01-iam-creation.yaml\"}"

**Comment by apawloski** [comment]
Hi Nic, I think that's exactly what's failing. That `TemplateURL` should be parameterized in `root.yml` to point to an arbitrary bucket.

I'll add that parameter, and then also add a script to push the templates to S3 in an organized way.

**Comment by apawloski** [comment]
Ok, this should be resolved in this commit: https://github.com/Element84/pangeo-deployment/commit/6e2059a15518fb2b0b5144e93973e3567f39976e

Note that there is now a variable to set in `deploy` which is the s3 location of the cf templates. It expects filenames to be preserved, and for them all to be in a flat prefix. 

I feel like an externalized config file will come out of this effort eventually -- I'm sure there are other E84-specific items throughout the stack here.

**Comment by NicWayand** [comment]
Thanks @apawloski! That fixed the error. If I find any more hard coded stuff I will make a PR.

now on to the next error.. "The following resource(s) failed to create: [InternetGateway, VPC]"
